//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotifySetRange
    {
        public int Id { get; set; }
        public string AquariumUnitNum { get; set; }
        public string temperatureUpperBound { get; set; }
        public string temperatureLowerBound { get; set; }
        public string pHUpperBound { get; set; }
        public string phLowerBound { get; set; }
        public string TDSUpperBound { get; set; }
        public string TDSLowerBound { get; set; }
        public string TurbidityUpperBound { get; set; }
        public string WaterLevelLowerBound { get; set; }
        public string NotifyTag { get; set; }
    }
}
