//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAquaruimSituation_ForMobile
    {
        public int Auth001Id { get; set; }
        public string AquariumUnitNum { get; set; }
        public string WaterType { get; set; }
        public string BindTag { get; set; }
        public int AquariumId { get; set; }
        public string temperature { get; set; }
        public string Turbidity { get; set; }
        public string PH { get; set; }
        public string TDS { get; set; }
        public string WaterLevel { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string WaterLevelNum { get; set; }
    }
}
